server:
  port: 8080
spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 26.26.26.1:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'